import React from "react";
import { FileText, ShieldCheck, Network, Download, CheckCircle2 } from "lucide-react";
import Card from "../components/common/Card";
import Badge from "../components/common/Badge";
export default function InvestigationReport(){
 return <div><div className="page-intro"><div><span className="eyebrow">FORENSIC OUTPUT</span><h2>Investigation Report</h2><p>Structured summary of recovery, reconstruction, validation and evidence provenance.</p></div><button className="primary-btn"><Download size={16}/> Export Report</button></div>
 <div className="report-grid"><Card><div className="report-cover"><div className="report-icon"><FileText size={30}/></div><span className="eyebrow">RECOVERAI FORENSIC REPORT</span><h3>Case IR-2026-014</h3><p>Damaged Storage Analysis</p><Badge tone="success">ANALYSIS COMPLETE â€” DEMO</Badge></div></Card><Card><div className="card-title">Recovery Summary</div><div className="report-metrics"><div><b>47</b><span>candidate files</span></div><div><b>31</b><span>reconstructed</span></div><div><b>91%</b><span>completeness</span></div><div><b>94%</b><span>structural integrity</span></div></div></Card></div>
 <div className="two-col"><Card><div className="card-title"><ShieldCheck/> Integrity Findings</div><div className="finding"><CheckCircle2/><div><b>31 files passed structural validation</b><p>File signatures, structural markers and parsers were checked where applicable.</p></div></div><div className="finding"><Network/><div><b>126 fragment relationships identified</b><p>Relationships are represented as candidates with confidence rather than absolute certainty.</p></div></div></Card><Card><div className="card-title">Evidence Chain</div><div className="chain">{["Evidence Source","Storage Region","Fragment Cluster","Reconstruction Candidate","Validation","Final Evidence"].map((x,i)=><div key={x}><span>{i+1}</span><b>{x}</b></div>)}</div></Card></div>
 <Card><div className="card-title">Forensic Classification</div><table><thead><tr><th>Classification</th><th>Meaning</th><th>Count</th></tr></thead><tbody><tr><td><Badge tone="success">Verified Recovery</Badge></td><td>Recovered and structurally verified evidence.</td><td>21</td></tr><tr><td><Badge tone="info">Structural Repair</Badge></td><td>Original bytes retained with structural repair.</td><td>10</td></tr><tr><td><Badge tone="warning">Plausible Reconstruction</Badge></td><td>Supported candidate reconstruction requiring review.</td><td>7</td></tr><tr><td><Badge tone="warning">AI-Inferred</Badge></td><td>Inference is explicitly not verified original data.</td><td>2</td></tr><tr><td><Badge tone="danger">Insufficient Evidence</Badge></td><td>Available evidence cannot support a reconstruction.</td><td>7</td></tr></tbody></table></Card>
 </div>
}
